package cli

// flags for exchange tx commands
const (
	FlagMarketID                 = "market-id"
	FlagMarketIDs                = "market-ids"
	FlagOrderType                = "order-type"
	FlagSubaccountID             = "subaccount-id"
	FlagPrice                    = "price"
	FlagQuantity                 = "quantity"
	FlagMargin                   = "margin"
	FlagTicker                   = "ticker"
	FlagBaseDenom                = "base-denom"
	FlagQuoteDenom               = "quote-denom"
	FlagOracleSymbol             = "oracle-symbol"
	FlagOracleProvider           = "oracle-provider"
	FlagAdmin                    = "admin"
	FlagOracleBase               = "oracle-base"
	FlagOracleQuote              = "oracle-quote"
	FlagOracleScaleFactor        = "oracle-scale-factor"
	FlagOracleType               = "oracle-type"
	FlagExpiry                   = "expiry"
	FlagSettlementTime           = "settlement-time"
	FlagInitialMarginRatio       = "initial-margin-ratio"
	FlagMaintenanceMarginRatio   = "maintenance-margin-ratio"
	FlagMakerFeeRate             = "maker-fee-rate"
	FlagTakerFeeRate             = "taker-fee-rate"
	FlagRelayerFeeShareRate      = "relayer-fee-share-rate"
	FlagHourlyInterestRate       = "hourly-interest-rate"
	FlagHourlyFundingRateCap     = "hourly-funding-rate-cap"
	FlagMinPriceTickSize         = "min-price-tick-size"
	FlagMinQuantityTickSize      = "min-quantity-tick-size"
	FlagMarketStatus             = "market-status"
	FlagTradingRewardCampaigns   = "campaigns"
	FlagSpotMarketIDs            = "spot-market-ids"
	FlagSpotMarketWeights        = "spot-market-weights"
	FlagDerivativeMarketIDs      = "derivative-market-ids"
	FlagDerivativeMarketWeights  = "derivative-market-weights"
	FlagMaxEpochRewards          = "max-epoch-rewards"
	FlagFeeRecipient             = "fee-recipient"
	FlagTriggerPrice             = "trigger-price"
	FlagReduceOnly               = "reduce-only"
	FlagOrderHash                = "order-hash"
	FlagSettlementPrice          = "settlement-price"
	FlagDecimals                 = "decimals"
	FlagDenom                    = "denom"
	FlagDenoms                   = "denoms"
	FlagExpirationTime           = "expiration-time"
	FlagSubscriptionQuoteAmount  = "quote-amount"
	FlagSubscriptionBaseAmount   = "base-amount"
	FlagSubscriptionMaxPenalty   = "max-penalty"
	FlagSubscriptionMinIncentive = "min-incentive"
)
