version: "2"
run:
  tests: false
linters:
  enable:
    - errorlint
    - gocritic
    - misspell
    - prealloc
    - revive
    - unconvert
    - unparam
  settings:
    gocritic:
      disabled-checks:
        - singleCaseSwitch
        - deferInLoop
        - hugeParam
        - unnamedResult
      enabled-tags:
        - performance
        - diagnostic
        - style
        - opinionated
        - experimental
    revive:
      enable-all-rules: true
      rules:
        - name: var-naming
          arguments:
            - - ID
        - name: add-constant
          disabled: true
        - name: line-length-limit
          arguments:
            - 140
        - name: cognitive-complexity
          arguments:
            - 20
          disabled: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - revive
        text: ALL_CAPS
    paths:
      - scripts/align_deps.go
      - injective-chain/modules/peggy/testpeggy
      - injective-chain/modules/exchange/testexchange
      - injective-chain/modules/exchange/client/testutil
      - injective-chain/stream/test
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
